jdk: oraclejdk8
language: scala
sudo: false
script: sbt scripted
cache:
  directories:
    - $HOME/.ivy2/cache
before_cache:
  # Ensure changes to the cache aren't persisted
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.sbt/sbt-less
  # Delete all ivydata files since ivy touches them on each build
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
